# S-57 Data Conversion Workflows

This notebook converts S-57 Electronic Navigational Charts (ENCs) to GIS backends (PostGIS, GeoPackage, SpatiaLite) for maritime analysis and routing.

#### Purpose

- **Quick Testing**: Fast one-to-one conversions with S57Base (5-30 min)
- **Production Databases**: Unified layer-centric conversions with S57Advanced (2-8 hours) - RECOMMENDED
- **Incremental Updates**: Maintain production databases with latest chart editions using S57Updater

#### Workflow Overview

1. **Configuration** - Select backend (PostGIS/GeoPackage/SpatiaLite) and conversion methods
2. **S57Base (Optional)** - One ENC = One output database for quick testing
3. **S57Advanced (Recommended)** - All ENCs = Unified database organized by layer
4. **S57Updater (Optional)** - Incremental updates to existing databases
5. **Verification** - Validate conversion integrity with data managers

#### Data Flow

```
S-57 Files (.000) → S57Base/S57Advanced → Backend (PostGIS/GeoPackage/SpatiaLite) → Verification
```

#### Expected Outputs

- **S57Base**: Multiple output databases (one per ENC) in `by_enc/` directory
- **S57Advanced**: Single unified database with all layers (e.g., `enc_west.gpkg` or PostGIS schema)
- **S57Updater**: Updated database with change summary showing edition/update changes

#### Required Data

This notebook requires:
1. **S-57 ENC Files**: `.000` base files in `data/ENC_ROOT/` or `data/ENC_SF_LA/ENC_ROOT/`
2. **PostgreSQL** (if using PostGIS): Database running with PostGIS extension
3. **Environment Variables**: Database credentials in `.env` file (PostGIS only)

**Setup Instructions:** See `docs/getting-started/setup.md`
**Troubleshooting:** See `docs/reference/troubleshooting.md`

 ## 1. Configuration

  All user-configurable parameters for the S-57 conversion pipeline are centralized below for easy modification. Select your target backend (PostGIS, GeoPackage, or SpatiaLite), choose which conversion methods to run (S57Base for quick testing, S57Advanced for production), and customize output paths and database settings. Adjust these parameters
  before running the notebook to control the entire conversion workflow.

In [1]:
# =============================================================================
# NOTEBOOK CONFIGURATION - Adjust these parameters before running
# =============================================================================

# --- Backend Selection (choose one) ---
# Options: 'postgis', 'spatialite', 'gpkg'
backend = 'postgis'

# --- Conversion Methods ---
# Select which S-57 conversion methods to run
methods = {
    'S57_Base': False,       # Quick one-to-one conversion (5-30 minutes)
    'S57_Advanced': True,   # Production layer-centric conversion (2-8 hours) - RECOMMENDED
    'S57_Updater': False    # Incremental updates to existing database (10-30 minutes)
}

# --- Additional Workflow Options ---
# PostGIS-only features and integration testing
workflow_options = {
    'run_parallel_processing': True,  # PostGIS only - test parallel file discovery

}

# --- Output Configuration ---
# Base name for all S57Advanced and S57Updater outputs (schemas and filenames)
# Change this single variable to rename all related outputs
output_base_name = 'enc_west'

# Derived output configuration (automatically generated from base name)
output_config = {
    # S57Base output (by_enc mode) - one database per ENC
    'base_output_dir': 'by_enc',
    
    # S57Advanced configurations (all use output_base_name)
    'pg_schema': output_base_name,
    'gpkg_filename': f'{output_base_name}.gpkg',
    'sqlite_filename': f'{output_base_name}.sqlite',
    
    # Parallel processing test configuration (separate schema for testing)
    'parallel_schema': 's57_parallel_test',
    
    # S57Updater configuration (uses same base name)
    'updater_schema': output_base_name,
    'updater_encs': ['US3CA52M', 'US1GC09M'],  # Specific ENCs to update
    'updater_gpkg': f'{output_base_name}.gpkg',
    'updater_sqlite': f'{output_base_name}.sqlite',

}

# --- S57Updater Configuration ---
# Control update behavior when methods['S57_Updater'] is enabled
updater_config = {
    'force_update': False,  # True: Replace ENCs entirely | False: Apply incremental updates
}


# --- Configuration Summary ---
print("=" * 70)
print("✓ Configuration loaded successfully!")
print("=" * 70)
print(f"\n📦 Backend: {backend.upper()}")
print(f"📊 Methods:")
print(f"   - S57_Base: {methods['S57_Base']}")
print(f"   - S57_Advanced: {methods['S57_Advanced']}")
print(f"   - S57_Updater: {methods['S57_Updater']}")
if backend == 'postgis':
    print(f"   - Parallel Processing: {workflow_options['run_parallel_processing']}")
if methods['S57_Updater']:
    update_mode = "Force update (replace ENCs)" if updater_config['force_update'] else "Normal update (incremental)"
    print(f"\n🔄 S57Updater mode: {update_mode}")
print(f"\n📁 Output base name: {output_base_name}")
print(f"   - S57Advanced schema/file: {output_config['pg_schema']}")
print(f"   - S57Updater schema/file: {output_config['updater_schema']}")
print("=" * 70)
print("\n⚠️  Paths and database parameters will be set after STEP 2: IMPORTS")
print("   (These depend on project_root and environment variables)")
print("=" * 70)

======================================================================
✓ Configuration loaded successfully!
======================================================================

📦 Backend: POSTGIS
📊 Methods:
   - S57_Base: False
   - S57_Advanced: True
   - S57_Updater: False
   - Parallel Processing: True

📁 Output base name: enc_west_new
   - S57Advanced schema/file: enc_west_new
   - S57Updater schema/file: enc_west_new
======================================================================

⚠️  Paths and database parameters will be set after STEP 2: IMPORTS
   (These depend on project_root and environment variables)
======================================================================

### 1.1 Imports & Environment Setup

In [2]:
# =============================================================================
# IMPORTS - Consolidated import statements for all notebook dependencies
# =============================================================================

# --- Standard Library ---
import sys
import os
import logging
from pathlib import Path

# --- Environment Setup ---
from dotenv import load_dotenv

# --- Geospatial Libraries ---
from osgeo import gdal
import pandas as pd
import geopandas as gpd
import fiona

# --- Jupyter/Display ---
from IPython.display import display

# --- Fix PROJ_LIB Path (Common Conda/Jupyter Issue) ---
# Ensure GDAL/PROJ can find the coordinate database
conda_prefix = sys.prefix
possible_proj_lib = os.path.join(conda_prefix, 'share', 'proj')
if os.path.exists(possible_proj_lib):
    os.environ['PROJ_LIB'] = possible_proj_lib

# --- Environment Initialization ---
# Get project root for .env file loading
project_root = Path.cwd().parent.parent
sys.path.insert(0, str(project_root))  # ⭐ CRITICAL: Enables test imports

# --- Validate Project Root ---
if not (project_root / "src" / "nautical_graph_toolkit").exists():
    raise FileNotFoundError(
        f"❌ Invalid project root: {project_root}\n"
        f"   Expected to find src/nautical_graph_toolkit/\n"
        f"   Notebooks must be run from docs/notebooks/ directory"
    )

# --- S-57 Data Processing Core Classes ---
from nautical_graph_toolkit.core.s57_data import (
    S57Base,
    S57Advanced,
    S57Updater,
    PostGISManager,
    SpatiaLiteManager,
    GPKGManager,
    S57AdvancedConfig
)

# --- Database Connectivity ---
from nautical_graph_toolkit.utils.db_utils import PostGISConnector

# Load environment variables (.env file should be at project root)
load_dotenv(project_root / ".env")

print("✓ All imports loaded successfully!")

ERROR 1: PROJ: proj_create_from_database: Open of /home/vikont/miniforge3/envs/nautical/share/proj failed

✓ All imports loaded successfully!

### 1.2 Environment Validation

In [3]:
# Check GDAL version (always runs - no flag to skip)
print("=" * 70)
print("GDAL and Library Versions:")
print("=" * 70)
print(f"✓ Python path includes: {project_root}")
print(f"GDAL Python bindings version: {gdal.__version__}")
print(f"GDAL C library version: {gdal.VersionInfo('RELEASE_NAME')}")
print(f"GeoPandas version: {gpd.__version__}")
print(f"Fiona version: {fiona.__version__}")
print("=" * 70)

======================================================================
GDAL and Library Versions:
======================================================================
✓ Python path includes: /home/vikont/PythonProject/Nautical-Graph-Toolkit
GDAL Python bindings version: 3.10.3
GDAL C library version: 3.10.3
GeoPandas version: 1.1.2
Fiona version: 1.10.1
======================================================================

### 1.3 Workflow Context

This notebook is **Step 1 of the 3-Step Maritime Processing Pipeline**:

| Position | Notebook | Purpose | Duration |
|----------|----------|---------|----------|
| **Step 1 (You are here)** | **import_s57.ipynb** | Convert S-57 ENC files to GIS backends (PostGIS, GeoPackage, SpatiaLite) | 5-30 min to 8 hours |
| **Step 2** | `graph_*.ipynb` | Build routing graphs from converted layers (optional, for analysis) | 1-2 hours |
| **Step 3** | `maritime_graph_*_workflow.py` | Integrate with production routing and maritime applications | Ongoing |

**Prerequisites:**
- S-57 ENC files in `data/ENC_ROOT/` directory
- PostgreSQL + PostGIS extension (if using PostGIS backend)
- Environment variables configured in `.env` file (PostGIS only)

**Outputs Generated:**
- Converted databases in selected backend (PostGIS schema, GeoPackage file, or SpatiaLite file)
- Layer-organized structure with feature stamping (dsid_* columns)
- Ready-to-use spatial data for maritime routing and analysis

**Next Steps After Completion:**
1. Build routing graphs: `graph_PostGIS_v2.ipynb` or `graph_fine_PostGIS_v2.ipynb`
2. Deploy to production: `maritime_graph_postgis_workflow.py`
3. (Optional) Test with `import_deeptest.ipynb` for comprehensive validation

### 1.4 Data Paths and Database Setup

Now that imports are complete, set up data paths and database connection parameters.

In [4]:
# --- Data Source Paths ---
# Define locations for input ENC data and output databases
data_paths = {
    # Primary ENC data directory (used for S57Advanced large-scale conversions)
    # Contains complete NOAA ENC dataset for comprehensive testing
    'active_enc': project_root / 'data' / 'ENC_SF_LA' / 'ENC_ROOT',
    
    # Test/sample ENC data directory (used for S57Base and smaller tests)
    # Contains subset of ENCs for quick conversions and verification
    's57_data_dir': project_root / 'data' / 'ENC_ROOT',
    
    # ENC update files (used by S57Updater for incremental updates)
    # Contains newer chart updates to test update mechanisms
    's57_data_update_dir': project_root / 'data' / 'ENC_ROOT_UPDATE',
    
    # Output directory for all conversion results
    'output_dir': project_root / 'data',

}

# Validate critical paths exist before proceeding
# This prevents silent failures if data directories are missing
print("Validating data paths...")
required_paths = {
    's57_data_dir': data_paths['s57_data_dir'],
    'output_dir': data_paths['output_dir']
}

for path_name, path in required_paths.items():
    if path.exists():
        print(f"  ✓ {path_name}: {path}")
    else:
        print(f"  ⚠️  {path_name} does not exist: {path}")
        print(f"     Create this directory or adjust data_paths configuration.")

# --- Database Connection Parameters ---
# PostGIS connection details (from .env file)
# Only used when backend = 'postgis'
db_params = {
    'dbname': os.getenv('DB_NAME'),
    'user': os.getenv('DB_USER'),
    'password': os.getenv('DB_PASSWORD'),
    'host': os.getenv('DB_HOST'),
    'port': os.getenv('DB_PORT')
}

# Validate PostGIS environment variables if using PostGIS backend
if backend == 'postgis':
    print("\nValidating PostGIS environment variables...")
    required_env_vars = ['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_PORT']
    missing_vars = [var for var in required_env_vars if not os.getenv(var)]
    
    if missing_vars:
        raise ValueError(
            f"❌ Missing required environment variables: {missing_vars}\n"
            f"\nPostGIS backend requires database credentials in .env file.\n"
            f"Create a .env file in the project root with:\n"
            f"  DB_NAME=maritime_db\n"
            f"  DB_USER=your_user\n"
            f"  DB_PASSWORD=your_password\n"
            f"  DB_HOST=localhost\n"
            f"  DB_PORT=5432\n"
        )
    print("  ✓ All database environment variables are set")
    print(f"    - Database: {db_params['dbname']}")
    print(f"    - Host: {db_params['host']}:{db_params['port']}")

# --- S57Advanced Configuration Objects ---
# Define conversion behavior for different scenarios
s57_advanced_config = {
    # Default configuration: auto-tuned batch processing
    # Recommended for most conversions - balances speed and memory
    'default': S57AdvancedConfig(
        auto_tune_batch_size=True,
        enable_debug_logging=False
    ),

    # Parallel processing configuration: high-safety read-only approach
    # Safe for production - only parallelizes file discovery, not database writes
    'parallel': S57AdvancedConfig(
        enable_parallel_processing=True,    # Use multiple cores
        parallel_read_only=True,            # Read-only operations only
        parallel_db_writes=False,           # Writes are sequential
        parallel_validation_level='strict', # Maximum data quality checks
        max_parallel_workers=2,             # Conservative worker count for stability
        enable_debug_logging=False          # Disable debug logging during config creation
    )
}

# --- Summary ---
print("=" * 70)
print("✓ Paths and Database Parameters Configured!")
print("=" * 70)
print(f"\n📁 Data directories:")
print(f"   - Active ENC: {data_paths['active_enc']}")
print(f"   - Test ENC:   {data_paths['s57_data_dir']}")
print(f"   - Output:     {data_paths['output_dir']}")
if backend == 'postgis':
    print(f"\n🗄️  PostGIS Connection:")
    print(f"   - Database: {db_params.get('dbname', 'NOT CONFIGURED')}")
    print(f"   - Host:     {db_params.get('host', 'NOT CONFIGURED')}")
print("=" * 70)

Validating data paths...
  ✓ s57_data_dir: /home/vikont/PythonProject/Nautical-Graph-Toolkit/data/ENC_ROOT
  ✓ output_dir: /home/vikont/PythonProject/Nautical-Graph-Toolkit/data

Validating PostGIS environment variables...
  ✓ All database environment variables are set
    - Database: enc_db
    - Host: localhost:5433
======================================================================
✓ Paths and Database Parameters Configured!
======================================================================

📁 Data directories:
   - Active ENC: /home/vikont/PythonProject/Nautical-Graph-Toolkit/data/ENC_SF_LA/ENC_ROOT
   - Test ENC:   /home/vikont/PythonProject/Nautical-Graph-Toolkit/data/ENC_ROOT
   - Output:     /home/vikont/PythonProject/Nautical-Graph-Toolkit/data

🗄️  PostGIS Connection:
   - Database: enc_db
   - Host:     localhost
======================================================================

### 1.5 PostGIS Connection Test

In [5]:
# =============================================================================
# PostGIS Connection Test
# =============================================================================
# IMPORTANT: Test the database connection early for PostGIS backend
# This ensures all PostGIS operations will succeed before proceeding.

if backend == 'postgis':
    print("=" * 70)
    print("Testing PostGIS database connection...")
    print("=" * 70)
    try:
        pg = PostGISConnector(db_params)
        pg.connect()
        schemas = pg.get_schemas()
        print(f"✓ PostGIS connection successful!")
        print(f"✓ Available schemas: {schemas}")
        print("=" * 70)
    except Exception as e:
        print(f"✗ PostGIS connection failed: {e}")
        print("  Please check your .env file and database credentials before proceeding.")
        print("=" * 70)
else:
    print("=" * 70)
    print(f"PostGIS connection test skipped (backend = '{backend}', not 'postgis')")
    print("=" * 70)

======================================================================
Testing PostGIS database connection...
======================================================================
2026-03-10 14:42:49,434 - nautical_graph_toolkit.utils.db_utils - INFO - Successfully connected to database 'enc_db' for schema management.
✓ PostGIS connection successful!
✓ Available schemas: ['deeptest_1768820129', 'enc_west', 'graph', 'public', 'routes', 's57_deeptest', 's57_parallel_test', 'tiger', 'tiger_data', 'topology', 'us1eez1m', 'us1gc09m', 'us1po02m', 'us2wc12m', 'us3ca52m', 'us4ca60m']
======================================================================

## 2. S57Base - Simple Bulk Conversion (by_enc mode)

`S57Base` is the simplest conversion class, creating one output per input S-57 file.

#### Key Characteristics

| Feature | Details |
|---------|---------|
| **Processing Mode** | One S-57 file → One output database/schema |
| **Tool Used** | GDAL's `VectorTranslate` |
| **Feature Stamping** | None - raw ENC data only |
| **Speed** | Fast - minutes to hours depending on ENC count |
| **Output Locations** | Multiple backends: GeoPackage, PostGIS, SpatiaLite |

#### Use Cases
- Initial ENC assessment and validation
- Isolated testing of specific charts
- Preserving individual ENC versions unchanged
- Quick conversions of small datasets
- Debugging specific ENC problems

#### What Happens During Conversion
1. Scans input directory for `.000` files (S-57 base files)
2. Uses GDAL's `VectorTranslate` for one-to-one mapping
3. Creates separate output per chart
4. Preserves original S-57 object class organization

#### Limitation
No feature stamping or cross-chart analysis capability - see S57Advanced for production use.

#### Comparison: S57Base vs S57Advanced

| Aspect | S57Base (by_enc) | S57Advanced (by_layer) |
|--------|------------------|----------------------|
| **Output Structure** | One database per ENC file | Single unified database with all ENCs |
| **Organization** | By source chart | By S-57 object class (layer) |
| **Feature Stamping** | None | Yes: `dsid_dsnm`, `dsid_edtn`, `dsid_updn` |
| **Cross-chart Analysis** | Limited | Excellent - all layers contain all relevant features |
| **Conversion Speed** | Fast (minutes) | Slow (hours) - but only needed once |
| **Best For** | Testing, QA, isolated analysis | Production integration, spatial queries, routing |
| **Data Duplication** | High - object classes repeated in each ENC | None - normalized by layer |
| **Spatial Queries** | Must query multiple databases | Single database query |

#### When to Use Each Mode

**Use S57Base if you need to:**
- Quickly test a few ENC files
- Preserve original ENC boundaries and organization
- Work with individual chart editions
- Perform isolated validation checks

**Use S57Advanced if you need to:**
- Build a production maritime database
- Run spatial analysis across chart boundaries
- Support routing and pathfinding algorithms
- Track data provenance with `dsid_*` columns
- Minimize storage overhead

### 2.1 Convert to GeoPackage

In [6]:
# S57Base conversion to selected backend
if methods['S57_Base'] and backend == 'gpkg':
    # import logging
    # logging.getLogger('src.nautical_graph_toolkit.core.s57_data').setLevel(logging.DEBUG)

    base_converter = S57Base(
            input_path=data_paths['s57_data_dir'],
            output_dest=str(data_paths['output_dir'] / 'by_enc'),
            output_format='gpkg',
            overwrite=True
        )
    base_converter.convert_by_enc()
elif methods['S57_Base']:
    print(f"S57Base GeoPackage conversion skipped (backend = '{backend}', not 'gpkg')")
else:
    print("S57Base conversion skipped (methods['S57_Base'] = False)")

S57Base conversion skipped (methods['S57_Base'] = False)

### 2.2 Convert to PostGIS

In [7]:
# S57Base conversion to PostGIS
if methods['S57_Base'] and backend == 'postgis':
    base_converter = S57Base(
            input_path=data_paths['s57_data_dir'],
            output_dest=db_params,
            output_format='postgis',
            overwrite=False
        )
    base_converter.convert_by_enc()
elif methods['S57_Base']:
    print(f"S57Base PostGIS conversion skipped (backend = '{backend}', not 'postgis')")
else:
    print("S57Base conversion skipped (methods['S57_Base'] = False)")

S57Base conversion skipped (methods['S57_Base'] = False)

In [8]:
# Verify PostGIS schema after S57Base conversion
if methods['S57_Base'] and backend == 'postgis':
    pg = PostGISConnector(db_params)
    pg.connect()
    pg.get_schema_summary()
elif methods['S57_Base']:
    print(f"PostGIS schema verification skipped (backend = '{backend}', not 'postgis')")
else:
    print("PostGIS schema verification skipped (S57Base conversion not enabled)")

PostGIS schema verification skipped (S57Base conversion not enabled)

### 2.3 Convert to SpatiaLite

In [9]:
# S57Base conversion to SpatiaLite
if methods['S57_Base'] and backend == 'spatialite':
    base_converter = S57Base(
            input_path=data_paths['s57_data_dir'],
             output_dest=str(data_paths['output_dir'] / 'by_enc'),
            output_format='spatialite',
            overwrite=True
        )
    base_converter.convert_by_enc()
elif methods['S57_Base']:
    print(f"S57Base SpatiaLite conversion skipped (backend = '{backend}', not 'spatialite')")
else:
    print("S57Base conversion skipped (methods['S57_Base'] = False)")

S57Base conversion skipped (methods['S57_Base'] = False)

## 3. S57Advanced - Optimized Layer-Centric Conversion (by_layer mode) - RECOMMENDED

`S57Advanced` performs optimized, layer-centric conversion merging all inputs into a unified database. **This is the recommended approach for production maritime databases.**

#### Key Features

| Feature | Benefit |
|---------|---------|
| **Layer-centric organization** | All data organized by S-57 object class (e.g., all soundings together) - enables powerful spatial queries |
| **Feature stamping** | Each feature tagged with source ENC (`dsid_dsnm`), edition (`dsid_edtn`), update (`dsid_updn`) - full data lineage |
| **Batch processing** | Optimized memory management with `auto_tune_batch_size` - handles 10000+ ENCs |
| **Parallel processing** | Optional multi-threaded file discovery (read-only) - faster preprocessing |
| **Auto-tuning** | Automatically adjusts batch size based on available memory - no manual tuning needed |

#### Use Cases
- **Production data integration**: Build comprehensive maritime databases supporting multi-user access
- **Spatial analysis**: Query all features of a type across all charts (e.g., "all lights in US waters")
- **Routing and pathfinding**: Need unified navigable area representation for navigation algorithms
- **Data fusion**: Combine S-57 with other maritime data sources
- **Historical tracking**: Use `dsid_edtn` and `dsid_updn` columns to analyze chart evolution

#### Configuration Options
- `auto_tune_batch_size`: Let system optimize performance automatically (recommended)
- `enable_parallel_processing`: Use multiple cores for file discovery
- `parallel_validation_level`: Balance speed vs. data quality checks ('strict' is recommended)

#### Why Layer-Centric is Better for Production
1. **Single Query**: One SQL query gets all relevant features instead of querying 100+ databases
2. **Data Integrity**: Feature stamping ensures traceability of data sources
3. **Performance**: Spatial indexes optimized for layer-based queries
4. **Consistency**: All features in a layer have uniform attributes and structure

### 3.1 Convert to PostGIS

In [10]:
# S57Advanced conversion to PostGIS
if methods['S57_Advanced'] and backend == 'postgis':
    pg_schema = output_config['pg_schema']
    print("=" * 70)
    print(f"STARTING S57Advanced PostGIS Conversion")
    print("=" * 70)
    print(f"Target Schema: {pg_schema}")
    print(f"Data Source: {data_paths['active_enc']}")
    print(f"Estimated Duration: 2-4 hours (depends on CPU cores and I/O speed)")
    print("=" * 70)
    
    try:
        # --- Step 1: Conversion ---
        print("\n📦 Step 1/2: Converting S-57 ENCs to unified layer-centric database...")
        print("   Progress: This is a long operation (2-4 hours). Keep this cell in focus.")
        print("   ⏱️  Started at:", pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"))
        
        advanced_converter_pg = S57Advanced(
            input_path=data_paths['active_enc'],
            output_dest=db_params,
            output_format='postgis',
            overwrite=True,
            schema=pg_schema,
            config=s57_advanced_config['default']
        )
        advanced_converter_pg.convert_to_layers()
        
        print("   ✅ Conversion completed!")
        print("   ⏱️  Completed at:", pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"))
        
        print("\n🔍 Step 2/2: Verifying conversion integrity...")
        # --- Step 2: Verification ---
        try:
            manager = PostGISManager(db_params=db_params, schema=pg_schema)

            # Verify a common layer exists and has data
            depare_layer = manager.get_layer('lndmrk')
            print(f"   ✅ Loaded {len(depare_layer)} features from LNDMRK layer.")
            print("   LNDMRK layer head (note the 'dsid_*' stamping columns):")
            display(depare_layer.head())

            # Verify feature stamping integrity across all layers
            print("\n   Verifying feature update status against DSID table...")
            verification_results = manager.verify_feature_update_status()
            print("   ✅ Verification Summary:")
            display(verification_results)
            
            print("\n" + "=" * 70)
            print("✅ S57Advanced PostGIS conversion COMPLETED SUCCESSFULLY")
            print("=" * 70)

        except Exception as e:
            print(f"   ⚠️  Verification failed (but conversion may have succeeded): {e}")
            print("   This is non-critical - the data may still be usable.")
            raise
            
    except RuntimeError as e:
        print("\n" + "=" * 70)
        print("❌ S57Advanced PostGIS CONVERSION FAILED")
        print("=" * 70)
        print(f"\nError: {e}")
        print("\nPossible causes and recovery steps:")
        print("1. DATABASE CONNECTIVITY:")
        print("   - Check: psql -U {db_params['user']} -h {db_params['host']} -d {db_params['dbname']}")
        print("   - Verify database is running and accessible")
        print("2. DISK SPACE:")
        print("   - Run: df -h | grep -E '^/|postgre'")
        print("   - PostGIS needs 2-3x the source ENC file size")
        print("3. MEMORY:")
        print("   - Check available RAM: free -h")
        print("   - Try disabling parallel processing: workflow_options['run_parallel_processing'] = False")
        print("4. DATA CORRUPTION:")
        print("   - Verify source ENC files: ls -la {data_paths['active_enc']}")
        print("   - Check for truncated or corrupted .000 files (should be 100KB+)")
        print("5. RECOVERY:")
        print(f"   - Drop the schema: psql -U {db_params['user']} -d {db_params['dbname']} -c 'DROP SCHEMA IF EXISTS {pg_schema} CASCADE'")
        print("   - Re-run this cell after fixing the issue")
        print("=" * 70)
        raise
        
elif methods['S57_Advanced']:
    print(f"S57Advanced PostGIS conversion skipped (backend = '{backend}', not 'postgis')")
else:
    print("S57Advanced conversion skipped (methods['S57_Advanced'] = False)")

======================================================================
STARTING S57Advanced PostGIS Conversion
======================================================================
Target Schema: enc_west_new
Data Source: /home/vikont/PythonProject/Nautical-Graph-Toolkit/data/ENC_SF_LA/ENC_ROOT
Estimated Duration: 2-4 hours (depends on CPU cores and I/O speed)
======================================================================

📦 Step 1/2: Converting S-57 ENCs to unified layer-centric database...
   Progress: This is a long operation (2-4 hours). Keep this cell in focus.
   ⏱️  Started at: 2026-03-10 14:42:49
2026-03-10 14:42:49,499 - nautical_graph_toolkit.core.s57_data - INFO - Found 21 S-57 file(s).
2026-03-10 14:42:49,499 - nautical_graph_toolkit.core.s57_data - INFO - --- Starting optimized 'by_layer' conversion ---
2026-03-10 14:42:49,500 - nautical_graph_toolkit.core.s57_data - INFO - Files to process: 21, Batch size: 10
2026-03-10 14:42:49,500 - nautical_graph_toolkit.core.s57_data - INFO - Pre-processing files to extract schemas and ENC names...
2026-03-10 14:42:49,680 - nautical_graph_toolkit.core.s57_data - INFO - Built unified schemas for 101 layers
2026-03-10 14:42:49,681 - nautical_graph_toolkit.utils.db_utils - INFO - Successfully connected to database 'enc_db' for schema management.
2026-03-10 14:42:49,691 - nautical_graph_toolkit.utils.db_utils - WARNING - Overwrite is enabled. Dropping and recreating schema 'enc_west_new'...
2026-03-10 14:42:49,696 - nautical_graph_toolkit.utils.db_utils - INFO - Schema 'enc_west_new' is ready.
2026-03-10 14:42:49,696 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: DSID
2026-03-10 14:42:50,466 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'DSID' with 21 files
2026-03-10 14:42:50,467 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: IsolatedNode
2026-03-10 14:42:51,202 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'IsolatedNode' with 21 files
2026-03-10 14:42:51,202 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: ConnectedNode
2026-03-10 14:42:51,937 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'ConnectedNode' with 21 files
2026-03-10 14:42:51,938 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: Edge
2026-03-10 14:42:52,691 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'Edge' with 21 files
2026-03-10 14:42:52,692 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: Face
2026-03-10 14:42:53,449 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'Face' with 21 files
2026-03-10 14:42:53,449 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: ADMARE
2026-03-10 14:42:53,738 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'ADMARE' with 7 files
2026-03-10 14:42:53,738 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: ACHARE
2026-03-10 14:42:54,363 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'ACHARE' with 15 files
2026-03-10 14:42:54,364 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: BUISGL
2026-03-10 14:42:55,797 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'BUISGL' with 20 files
2026-03-10 14:42:55,797 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: BUAARE
2026-03-10 14:42:56,613 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'BUAARE' with 18 files
2026-03-10 14:42:56,614 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CTNARE
2026-03-10 14:42:57,336 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CTNARE' with 17 files
2026-03-10 14:42:57,337 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: COALNE
2026-03-10 14:42:59,678 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'COALNE' with 21 files
2026-03-10 14:42:59,679 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: DEPARE
2026-03-10 14:43:02,508 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'DEPARE' with 21 files
2026-03-10 14:43:02,509 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: DEPCNT
2026-03-10 14:43:05,301 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'DEPCNT' with 21 files
2026-03-10 14:43:05,302 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: LNDARE
2026-03-10 14:43:07,911 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'LNDARE' with 21 files
2026-03-10 14:43:07,912 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: LNDELV
2026-03-10 14:43:08,748 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'LNDELV' with 16 files
2026-03-10 14:43:08,749 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: LNDRGN
2026-03-10 14:43:09,925 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'LNDRGN' with 20 files
2026-03-10 14:43:09,926 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: LNDMRK
2026-03-10 14:43:10,697 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'LNDMRK' with 18 files
2026-03-10 14:43:10,698 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: LIGHTS
2026-03-10 14:43:11,742 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'LIGHTS' with 20 files
2026-03-10 14:43:11,743 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: MAGVAR
2026-03-10 14:43:12,633 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'MAGVAR' with 21 files
2026-03-10 14:43:12,634 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: MIPARE
2026-03-10 14:43:13,136 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'MIPARE' with 12 files
2026-03-10 14:43:13,136 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: MORFAC
2026-03-10 14:43:13,831 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'MORFAC' with 15 files
2026-03-10 14:43:13,832 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: OBSTRN
2026-03-10 14:43:15,039 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'OBSTRN' with 21 files
2026-03-10 14:43:15,040 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: RESARE
2026-03-10 14:43:16,079 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'RESARE' with 21 files
2026-03-10 14:43:16,079 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: RIVERS
2026-03-10 14:43:17,040 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'RIVERS' with 19 files
2026-03-10 14:43:17,040 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: SEAARE
2026-03-10 14:43:18,160 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'SEAARE' with 21 files
2026-03-10 14:43:18,161 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: SBDARE
2026-03-10 14:43:20,438 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'SBDARE' with 21 files
2026-03-10 14:43:20,439 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: SLCONS
2026-03-10 14:43:25,904 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'SLCONS' with 21 files
2026-03-10 14:43:25,904 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: SILTNK
2026-03-10 14:43:26,554 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'SILTNK' with 15 files
2026-03-10 14:43:26,555 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: SOUNDG
2026-03-10 14:43:44,854 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'SOUNDG' with 21 files
2026-03-10 14:43:44,854 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: TSSBND
2026-03-10 14:43:45,068 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'TSSBND' with 5 files
2026-03-10 14:43:45,068 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: TSSLPT
2026-03-10 14:43:45,288 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'TSSLPT' with 5 files
2026-03-10 14:43:45,289 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: TSEZNE
2026-03-10 14:43:45,473 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'TSEZNE' with 4 files
2026-03-10 14:43:45,473 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: UWTROC
2026-03-10 14:43:48,116 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'UWTROC' with 18 files
2026-03-10 14:43:48,116 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: WEDKLP
2026-03-10 14:43:49,270 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'WEDKLP' with 18 files
2026-03-10 14:43:49,270 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: WRECKS
2026-03-10 14:43:50,093 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'WRECKS' with 19 files
2026-03-10 14:43:50,094 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: M_CSCL
2026-03-10 14:43:50,519 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'M_CSCL' with 10 files
2026-03-10 14:43:50,520 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: M_COVR
2026-03-10 14:43:51,377 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'M_COVR' with 21 files
2026-03-10 14:43:51,378 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: M_NPUB
2026-03-10 14:43:52,222 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'M_NPUB' with 21 files
2026-03-10 14:43:52,222 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: M_NSYS
2026-03-10 14:43:53,074 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'M_NSYS' with 21 files
2026-03-10 14:43:53,074 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: M_QUAL
2026-03-10 14:43:54,404 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'M_QUAL' with 21 files
2026-03-10 14:43:54,405 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: C_AGGR
2026-03-10 14:43:54,837 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'C_AGGR' with 11 files
2026-03-10 14:43:54,837 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: C_ASSO
2026-03-10 14:43:55,113 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'C_ASSO' with 7 files
2026-03-10 14:43:55,114 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: BCNLAT
2026-03-10 14:43:55,671 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'BCNLAT' with 12 files
2026-03-10 14:43:55,673 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: BCNSPP
2026-03-10 14:43:56,444 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'BCNSPP' with 18 files
2026-03-10 14:43:56,445 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: BRIDGE
2026-03-10 14:43:56,974 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'BRIDGE' with 11 files
2026-03-10 14:43:56,975 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: BOYLAT
2026-03-10 14:43:57,627 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'BOYLAT' with 15 files
2026-03-10 14:43:57,628 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: BOYSAW
2026-03-10 14:43:57,996 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'BOYSAW' with 9 files
2026-03-10 14:43:57,997 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CBLARE
2026-03-10 14:43:58,437 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CBLARE' with 10 files
2026-03-10 14:43:58,437 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CBLOHD
2026-03-10 14:43:58,717 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CBLOHD' with 6 files
2026-03-10 14:43:58,718 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CANALS
2026-03-10 14:43:58,777 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CANALS' with 1 files
2026-03-10 14:43:58,778 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: DAYMAR
2026-03-10 14:43:59,432 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'DAYMAR' with 13 files
2026-03-10 14:43:59,433 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: DRGARE
2026-03-10 14:43:59,828 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'DRGARE' with 7 files
2026-03-10 14:43:59,828 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: DYKCON
2026-03-10 14:44:00,159 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'DYKCON' with 7 files
2026-03-10 14:44:00,159 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: FAIRWY
2026-03-10 14:44:00,583 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'FAIRWY' with 10 files
2026-03-10 14:44:00,583 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: FNCLNE
2026-03-10 14:44:00,803 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'FNCLNE' with 5 files
2026-03-10 14:44:00,803 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: FERYRT
2026-03-10 14:44:00,986 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'FERYRT' with 4 files
2026-03-10 14:44:00,987 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: FOGSIG
2026-03-10 14:44:01,554 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'FOGSIG' with 14 files
2026-03-10 14:44:01,555 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: LAKARE
2026-03-10 14:44:02,031 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'LAKARE' with 11 files
2026-03-10 14:44:02,031 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: NAVLNE
2026-03-10 14:44:02,417 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'NAVLNE' with 9 files
2026-03-10 14:44:02,417 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: OFSPLF
2026-03-10 14:44:02,765 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'OFSPLF' with 8 files
2026-03-10 14:44:02,765 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: PILPNT
2026-03-10 14:44:03,327 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'PILPNT' with 11 files
2026-03-10 14:44:03,328 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: PIPARE
2026-03-10 14:44:03,547 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'PIPARE' with 5 files
2026-03-10 14:44:03,548 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: ROADWY
2026-03-10 14:44:03,621 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'ROADWY' with 1 files
2026-03-10 14:44:03,622 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: SLOTOP
2026-03-10 14:44:04,288 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'SLOTOP' with 14 files
2026-03-10 14:44:04,289 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: SLOGRD
2026-03-10 14:44:04,633 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'SLOGRD' with 8 files
2026-03-10 14:44:04,634 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: AIRARE
2026-03-10 14:44:04,856 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'AIRARE' with 5 files
2026-03-10 14:44:04,856 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: BOYSPP
2026-03-10 14:44:05,297 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'BOYSPP' with 10 files
2026-03-10 14:44:05,298 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CBLSUB
2026-03-10 14:44:05,830 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CBLSUB' with 12 files
2026-03-10 14:44:05,831 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: DMPGRD
2026-03-10 14:44:06,055 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'DMPGRD' with 5 files
2026-03-10 14:44:06,056 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: PILBOP
2026-03-10 14:44:06,282 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'PILBOP' with 5 files
2026-03-10 14:44:06,283 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: PIPSOL
2026-03-10 14:44:06,818 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'PIPSOL' with 12 files
2026-03-10 14:44:06,819 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: PRDARE
2026-03-10 14:44:07,006 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'PRDARE' with 4 files
2026-03-10 14:44:07,007 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CTRPNT
2026-03-10 14:44:07,068 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CTRPNT' with 1 files
2026-03-10 14:44:07,069 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: TOPMAR
2026-03-10 14:44:07,217 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'TOPMAR' with 3 files
2026-03-10 14:44:07,218 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: WATTUR
2026-03-10 14:44:07,704 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'WATTUR' with 11 files
2026-03-10 14:44:07,705 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CONZNE
2026-03-10 14:44:07,765 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CONZNE' with 1 files
2026-03-10 14:44:07,765 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CRANES
2026-03-10 14:44:07,867 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CRANES' with 2 files
2026-03-10 14:44:07,868 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: EXEZNE
2026-03-10 14:44:07,929 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'EXEZNE' with 1 files
2026-03-10 14:44:07,930 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: HULKES
2026-03-10 14:44:08,073 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'HULKES' with 3 files
2026-03-10 14:44:08,073 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: CGUSTA
2026-03-10 14:44:08,256 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'CGUSTA' with 4 files
2026-03-10 14:44:08,257 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: PIPOHD
2026-03-10 14:44:08,361 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'PIPOHD' with 2 files
2026-03-10 14:44:08,362 - nautical_graph_toolkit.core.s57_data - INFO - Processing layer: PONTON
2026-03-10 14:44:08,908 - nautical_graph_toolkit.core.s57_data - INFO - -> Successfully processed layer 'PONTON' with 6 files

,ogc_fid,rcid,prim,grup,objl,rver,agen,fidn,fids,lnam,...,scamin,txtdsc,recdat,recind,sordat,sorind,dsid_dsnm,dsid_edtn,dsid_updn,wkb_geometry
0,1,150.0,1.0,2.0,74.0,1.0,550.0,4346202.0,3914.0,02260042515A0F4A,...,89999,None,None,None,200510,"US,US,graph,Chart 18729",US5CA67M,10,0,POINT (-119.55799 34.04475)
1,2,151.0,1.0,2.0,74.0,1.0,550.0,22310004.0,50.0,022601546C740032,...,89999,None,None,None,20131105,"US,US,reprt,11CGD,LNM 45/13",US5CA67M,10,0,POINT (-119.35957 34.01584)
2,3,152.0,1.0,2.0,74.0,1.0,550.0,4346204.0,3914.0,02260042515C0F4A,...,89999,None,None,None,200510,"US,US,graph,Chart 18729",US5CA67M,10,0,POINT (-119.63475 33.99509)
3,4,153.0,1.0,2.0,74.0,1.0,550.0,4346208.0,3914.0,0226004251600F4A,...,89999,None,None,None,200510,"US,US,graph,Chart 18729",US5CA67M,10,0,POINT (-119.63202 33.99053)
4,5,2968.0,1.0,2.0,74.0,1.0,550.0,4043043.0,4205.0,0226003DB123106D,...,21999,None,None,None,200307,"US,US,graph,Chart 18754",US5CA83M,16,0,POINT (-117.93788 33.63211)

   Verifying feature update status against DSID table...
2026-03-10 14:44:11,776 - nautical_graph_toolkit.core.s57_data - INFO - Feature update status verification complete: {'VALID': np.int64(965)}
   ✅ Verification Summary:

,layer_name,enc_name,dsid_edition,dsid_update,feature_edition,feature_update,feature_count,edition_match,update_match,status
19,achare,US5CA50M,12,10,12,10,2,True,True,VALID
15,achare,US5CA51M,9,0,9,0,2,True,True,VALID
10,achare,US5CA59M,6,3,6,3,2,True,True,VALID
16,achare,US5CA61M,50,3,50,3,10,True,True,VALID
9,achare,US5CA62M,67,4,67,4,13,True,True,VALID
...,...,...,...,...,...,...,...,...,...,...
508,wrecks,US5CA82M,12,1,12,1,1,True,True,VALID
503,wrecks,US5CA83M,16,0,16,0,1,True,True,VALID
497,wrecks,US5CA84M,8,0,8,0,4,True,True,VALID
502,wrecks,US5CA96M,11,1,11,1,7,True,True,VALID
505,wrecks,US5CA97M,8,0,8,0,5,True,True,VALID

======================================================================
✅ S57Advanced PostGIS conversion COMPLETED SUCCESSFULLY
======================================================================

### 3.2 Convert to GeoPackage

In [11]:
# S57Advanced conversion to GeoPackage
if methods['S57_Advanced'] and backend == 'gpkg':
    gpkg_path = data_paths['output_dir'] / output_config['gpkg_filename']
    print("=" * 70)
    print(f"STARTING S57Advanced GeoPackage Conversion")
    print("=" * 70)
    print(f"Output File: {gpkg_path}")
    print(f"Data Source: {data_paths['active_enc']}")
    print(f"Estimated Duration: 3-5 hours (GeoPackage is slower than PostGIS)")
    print("=" * 70)
    
    try:
        # --- Step 1: Conversion ---
        print("\n📦 Step 1/2: Converting S-57 ENCs to GeoPackage...")
        print("   Progress: This is a long operation (3-5 hours). Keep this cell in focus.")
        print("   ⏱️  Started at:", pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"))
        print(f"   Disk space needed: ~{int(data_paths['active_enc'].stat().st_size / (1024**3)) * 5}GB")

        advanced_converter_gpkg = S57Advanced(
            input_path=data_paths['active_enc'],
            output_dest=str(gpkg_path),
            output_format='gpkg',
            overwrite=True,
            config=s57_advanced_config['default']
        )
        advanced_converter_gpkg.convert_to_layers()

        print("   ✅ Conversion completed!")
        print("   ⏱️  Completed at:", pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"))
        print(f"   ✅ Output file size: {gpkg_path.stat().st_size / (1024**3):.1f}GB")

        print("\n🔍 Step 2/2: Verifying conversion integrity...")
        # --- Step 2: Verification ---
        try:
            manager = GPKGManager(gpkg_path=gpkg_path)

            # Verify a common layer exists and has data
            soundg_layer = manager.get_layer('lndmrk')
            print(f"   ✅ Loaded {len(soundg_layer)} features from LNDMRK layer in GeoPackage.")
            print("   LNDMRK layer head:")
            display(soundg_layer.head())

            # Verify feature stamping integrity
            print("\n   Verifying feature update status...")
            verification_results = manager.verify_feature_update_status()
            print("   ✅ Verification Summary:")
            display(verification_results)
            
            print("\n" + "=" * 70)
            print("✅ S57Advanced GeoPackage conversion COMPLETED SUCCESSFULLY")
            print("=" * 70)

        except Exception as e:
            print(f"   ⚠️  Verification failed (but conversion may have succeeded): {e}")
            print("   This is non-critical - the data may still be usable.")
            raise
            
    except RuntimeError as e:
        print("\n" + "=" * 70)
        print("❌ S57Advanced GeoPackage CONVERSION FAILED")
        print("=" * 70)
        print(f"\nError: {e}")
        print("\nPossible causes and recovery steps:")
        print("1. DISK SPACE:")
        print(f"   - Check: df -h {data_paths['output_dir']}")
        print(f"   - GeoPackage needs ~5x the source ENC file size")
        print(f"   - Free up space or change output_dir in configuration")
        print("2. FILE PERMISSIONS:")
        print(f"   - Check: ls -la {data_paths['output_dir']}")
        print(f"   - Ensure write permissions on output directory")
        print("3. CORRUPT SOURCE FILES:")
        print(f"   - Verify source ENCs: find {data_paths['active_enc']} -name '*.000' | xargs ls -lh")
        print(f"   - Check for truncated files (should be 100KB+)")
        print("4. GDAL/GDAL Issues:")
        print(f"   - Try restarting Jupyter kernel and re-running")
        print("5. RECOVERY:")
        print(f"   - Delete partial file: rm -f {gpkg_path}")
        print(f"   - Free up disk space or expand output directory")
        print(f"   - Re-run this cell after fixing the issue")
        print("=" * 70)
        raise
        
elif methods['S57_Advanced']:
    print(f"S57Advanced GeoPackage conversion skipped (backend = '{backend}', not 'gpkg')")
else:
    print("S57Advanced conversion skipped (methods['S57_Advanced'] = False)")

S57Advanced GeoPackage conversion skipped (backend = 'postgis', not 'gpkg')

### 3.3 Convert to SpatiaLite

In [12]:
# S57Advanced conversion to SpatiaLite
if methods['S57_Advanced'] and backend == 'spatialite':
    sqlite_path = data_paths['output_dir'] / output_config['sqlite_filename']
    print("=" * 70)
    print(f"STARTING S57Advanced SpatiaLite Conversion")
    print("=" * 70)
    print(f"Output File: {sqlite_path}")
    print(f"Data Source: {data_paths['active_enc']}")
    print(f"Estimated Duration: 1-2 hours (SpatiaLite is fastest file-based option)")
    print("=" * 70)
    
    try:
        # --- Step 1: Conversion ---
        print("\n📦 Step 1/2: Converting S-57 ENCs to SpatiaLite...")
        print("   Progress: This is a long operation (1-2 hours). Keep this cell in focus.")
        print("   ⏱️  Started at:", pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"))

        advanced_converter_sqlite = S57Advanced(
            input_path=data_paths['active_enc'],
            output_dest=str(sqlite_path),
            output_format='spatialite',
            overwrite=True,
            config=s57_advanced_config['default']
        )
        advanced_converter_sqlite.convert_to_layers()

        print("   ✅ Conversion completed!")
        print("   ⏱️  Completed at:", pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"))
        print(f"   ✅ Output file size: {sqlite_path.stat().st_size / (1024**3):.1f}GB")

        print("\n🔍 Step 2/2: Verifying conversion integrity...")
        # --- Step 2: Verification ---
        try:
            manager = SpatiaLiteManager(db_path=sqlite_path)

            # Verify a common layer exists and has data
            boyspp_layer = manager.get_layer('boyspp')
            print(f"   ✅ Loaded {len(boyspp_layer)} features from BOYSPP layer in SpatiaLite DB.")
            print("   BOYSPP layer head:")
            display(boyspp_layer.head())

            # Verify feature stamping integrity
            print("\n   Verifying feature update status...")
            verification_results = manager.verify_feature_update_status()
            print("   ✅ Verification Summary:")
            display(verification_results)
            
            print("\n" + "=" * 70)
            print("✅ S57Advanced SpatiaLite conversion COMPLETED SUCCESSFULLY")
            print("=" * 70)

        except Exception as e:
            print(f"   ⚠️  Verification failed (but conversion may have succeeded): {e}")
            print("   This is non-critical - the data may still be usable.")
            raise
            
    except RuntimeError as e:
        print("\n" + "=" * 70)
        print("❌ S57Advanced SpatiaLite CONVERSION FAILED")
        print("=" * 70)
        print(f"\nError: {e}")
        print("\nPossible causes and recovery steps:")
        print("1. DISK SPACE:")
        print(f"   - Check: df -h {data_paths['output_dir']}")
        print(f"   - SpatiaLite needs ~2-3x the source ENC file size")
        print(f"   - Free up space or change output_dir in configuration")
        print("2. FILE PERMISSIONS:")
        print(f"   - Check: ls -la {data_paths['output_dir']}")
        print(f"   - Ensure write permissions on output directory")
        print("3. CORRUPT SOURCE FILES:")
        print(f"   - Verify source ENCs: find {data_paths['active_enc']} -name '*.000' | xargs ls -lh")
        print(f"   - Check for truncated files (should be 100KB+)")
        print("4. SQLite LOCKS:")
        print(f"   - Check for stray locks: ls -la {data_paths['output_dir']}/*lock*")
        print(f"   - Kill blocking processes: lsof {sqlite_path} 2>/dev/null | grep -v COMMAND | awk '{{print $2}}' | xargs kill -9")
        print("5. RECOVERY:")
        print(f"   - Delete partial file: rm -f {sqlite_path}")
        print(f"   - Free up disk space")
        print(f"   - Re-run this cell after fixing the issue")
        print("=" * 70)
        raise
        
elif methods['S57_Advanced']:
    print(f"S57Advanced SpatiaLite conversion skipped (backend = '{backend}', not 'spatialite')")
else:
    print("S57Advanced conversion skipped (methods['S57_Advanced'] = False)")

S57Advanced SpatiaLite conversion skipped (backend = 'postgis', not 'spatialite')

### 3.4 Test with Enterprise-Safe Parallel Processing

In [13]:
# Test S57Advanced with Enterprise-Safe Parallel Processing (PostGIS only)
if workflow_options['run_parallel_processing'] and backend == 'postgis':
    # --- Step 1: Configure and Convert ---
    parallel_schema = output_config['parallel_schema']
    print(f"--- Starting S57Advanced conversion with PARALLEL processing to schema: '{parallel_schema}' ---")

    # Use the recommended high-safety configuration for parallel reads
    high_safety_config = s57_advanced_config['parallel']

    print("\nUsing configuration:")
    print(high_safety_config.get_configuration_summary())

    advanced_converter_parallel = S57Advanced(
        input_path=data_paths['s57_data_dir'],
        output_dest=db_params,
        output_format='postgis',
        overwrite=True,
        schema=parallel_schema,
        config=high_safety_config
    )
    advanced_converter_parallel.convert_to_layers()

    print("\n--- Step 2: Verification ---")
    # --- Step 2: Verification ---
    try:
        manager = PostGISManager(db_params=db_params, schema=parallel_schema)
        summary = manager.get_enc_summary()
        print(f"Successfully created {len(summary)} ENCs in the parallel-processed schema.")
        display(summary.head())
    except Exception as e:
        print(f"An error occurred during parallel processing verification: {e}")
elif workflow_options['run_parallel_processing']:
    print(f"Parallel processing test skipped (backend = '{backend}', not 'postgis')")
    print("Parallel processing is only available with PostGIS backend.")
else:
    print("Parallel processing test skipped (workflow_options['run_parallel_processing'] = False)")

--- Starting S57Advanced conversion with PARALLEL processing to schema: 's57_parallel_test' ---

Using configuration:
=== S57AdvancedConfig Summary ===
Batch Size: 25 (auto-tuned)
Target Memory: 512MB
Memory Limit: 1024MB
Average File Size: 8.0MB
Cache Schemas: True

=== Parallel Processing ===
Enabled: True
Max Workers: 2
Read-Only Mode: True
DB Writes: False
Validation Level: strict
🛡️  Enterprise Safety: HIGH (read-only parallelization)

=== Estimates ===
Estimated Peak Memory: 500.0MB
Available System Memory: 36408.1MB
Memory Usage Ratio: 1.4%

💡 INFO: Conservative memory usage - could increase batch_size for better performance
2026-03-10 14:44:11,879 - nautical_graph_toolkit.core.s57_data - INFO - Using enterprise-safe parallel processing
2026-03-10 14:44:11,893 - nautical_graph_toolkit.core.s57_data - INFO - --- Starting optimized 'by_layer' conversion ---
2026-03-10 14:44:11,894 - nautical_graph_toolkit.core.s57_data - INFO - Files to process: 0, Batch size: 1
2026-03-10 14:44:11,894 - nautical_graph_toolkit.core.s57_data - INFO - Parallel processing enabled with HIGH safety level
2026-03-10 14:44:11,894 - nautical_graph_toolkit.core.s57_data - INFO - Built unified schemas for 0 layers
2026-03-10 14:44:11,895 - nautical_graph_toolkit.utils.db_utils - INFO - Successfully connected to database 'enc_db' for schema management.
2026-03-10 14:44:11,904 - nautical_graph_toolkit.utils.db_utils - WARNING - Overwrite is enabled. Dropping and recreating schema 's57_parallel_test'...
2026-03-10 14:44:11,908 - nautical_graph_toolkit.utils.db_utils - INFO - Schema 's57_parallel_test' is ready.

--- Step 2: Verification ---
2026-03-10 14:44:11,909 - nautical_graph_toolkit.core.s57_data - INFO - Successfully connected to database 'enc_db'
An error occurred during parallel processing verification: (psycopg2.errors.UndefinedTable) relation "s57_parallel_test.dsid" does not exist
LINE 1: SELECT dsid_dsnm, dsid_edtn, dsid_updn FROM "s57_parallel_te...
                                                    ^

[SQL: SELECT dsid_dsnm, dsid_edtn, dsid_updn FROM "s57_parallel_test"."dsid"]
(Background on this error at: https://sqlalche.me/e/20/f405)

## 4. S57Updater - Incremental Updates

`S57Updater` handles incremental updates to an existing S57Advanced database, maintaining a production ENC database with latest chart updates.

#### Update Modes

| Mode | Method | Use Case | Configuration |
|------|--------|----------|---|
| **Force Update** | `force_update_from_location()` | Replace specific ENCs entirely (e.g., after fixing errors) | `updater_config['force_update'] = True` |
| **Normal Update** | `update_from_location()` | Apply incremental updates if available from NOAA | `updater_config['force_update'] = False` |

**Configure which mode to use in Step 1:**
```python
updater_config = {
    'force_update': True,  # True: Replace ENCs entirely | False: Apply incremental updates
}
```

#### How It Works
1. Compares local ENC versions with update files or source data
2. Re-converts and replaces features **only for changed ENCs** (fast!)
3. Maintains transaction integrity - all changes succeed or all fail (ACID)
4. Provides detailed change summaries showing before/after versions

#### Change Summary Information
After an update, you can see:
- Old Edition → New Edition for each updated ENC
- Update number changes tracking version history
- All changes recorded in database metadata tables

#### Backend Support

| Backend | Status | Notes |
|---------|--------|-------|
| **PostGIS** | ✅ Fully Supported | Transactional updates with full ACID guarantees |
| **SpatiaLite** | ⚠️ Use with Care | Works but can cause "database disk image is malformed" errors with concurrent access |
| **GeoPackage** | ⚠️ Use with Care | Similar issues to SpatiaLite with concurrent access |

#### Important Caution
Only use with PostGIS for production systems. File-based updates (SpatiaLite/GeoPackage) can cause corruption if the file is accessed by multiple uncoordinated connections simultaneously. **PostGIS is the only backend recommended for update operations in production.**

### 4.1 Example Update Summary Output

When running S57Updater with `force_update_from_location()`, you'll see output like this showing edition and update number changes for each ENC:

| Old Edition | New Edition |
|--|--|
| US1EEZ1M 9:0 | 9:0 |
| US1GC09M 65:5 | 71:1 |
| US1PO02M 21:1 | 21:1 |
| US2WC12M 27:8 | 27:12 |
| US3CA52M 31:0 | 31:7 |
| US4CA60M 37:6 | 38:2 |

The format is `ENC_NAME edition:update`. This example shows several ENCs were updated to newer editions/updates, while others (US1EEZ1M, US1PO02M) were already current.

### 4.2 PostGIS Updater

✅ **Production-ready** - Full transactional updates with ACID guarantees.

In [14]:
# Test S57Updater with selected backend
if methods['S57_Updater'] and backend == 'postgis':
    db_schema = output_config['updater_schema']
    updater = S57Updater(output_format='postgis',
                         dest_conn=db_params,
                         schema=db_schema)
    
    # Execute selected update mode based on configuration
    if updater_config['force_update']:
        print("Running force update (replacing specific ENCs)...")
        updater.force_update_from_location(
            data_paths['s57_data_dir'], 
            enc_filter=output_config['updater_encs']
        )
    else:
        print("Running normal incremental update...")
        updater.update_from_location(data_paths['s57_data_update_dir'])
    
    summary_df = updater.get_change_summary()
    display(summary_df)
elif methods['S57_Updater']:
    print(f"S57Updater PostGIS test skipped (backend = '{backend}', not 'postgis')")
else:
    print("S57Updater test skipped (methods['S57_Updater'] = False)")

S57Updater test skipped (methods['S57_Updater'] = False)

### 4.3 SpatiaLite Updater

⚠️ **Use with caution** - Can cause `database disk image is malformed` errors with concurrent access. 
PostGIS is recommended for production update operations. 

**See**: `docs/reference/troubleshooting.md` - "S57Updater: File-Based Backend Safety" section for detailed explanation and workarounds.

In [15]:
# Test S57Updater with SpatiaLite
if methods['S57_Updater'] and backend == 'spatialite':
    print("⚠️  WARNING: SpatiaLite updates can cause 'database disk image is malformed' errors")
    print("   PostGIS is recommended for production update operations.")
    print()
    
    sqlite_update_target_path = data_paths['output_dir'] / output_config['updater_sqlite']
    updater = S57Updater(
         output_format='spatialite',
         dest_conn=str(sqlite_update_target_path),
         schema='main' # SpatiaLite doesn't use schemas like PostGIS, but 'main' is the default
    )
    
    # Execute selected update mode based on configuration
    if updater_config['force_update']:
        print("Running force update (replacing specific ENCs)...")
        updater.force_update_from_location(
            data_paths['s57_data_dir'], 
            enc_filter=output_config['updater_encs']
        )
    else:
        print("Running normal incremental update...")
        updater.update_from_location(data_paths['s57_data_update_dir'])
    
    summary_df = updater.get_change_summary()
elif methods['S57_Updater']:
    print(f"S57Updater SpatiaLite test skipped (backend = '{backend}', not 'spatialite')")
else:
    print("S57Updater test skipped (methods['S57_Updater'] = False)")

S57Updater test skipped (methods['S57_Updater'] = False)

### 4.4 GeoPackage Updater

⚠️ **Use with caution** - Can cause corruption with concurrent access. 
PostGIS is recommended for production update operations.

In [16]:
# Test S57Updater with GeoPackage
if methods['S57_Updater'] and backend == 'gpkg':
    print("⚠️  WARNING: GeoPackage updates can cause corruption with concurrent access")
    print("   PostGIS is recommended for production update operations.")
    print()
    
    update_target_path = data_paths['output_dir'] / output_config['updater_gpkg']
    updater = S57Updater(
         output_format='gpkg',
         dest_conn=str(update_target_path),
         schema='main' # GeoPackage doesn't use schemas like PostGIS, but 'main' is the default
    )
    
    # Execute selected update mode based on configuration
    if updater_config['force_update']:
        print("Running force update (replacing specific ENCs)...")
        updater.force_update_from_location(
            data_paths['s57_data_dir'], 
            enc_filter=output_config['updater_encs']
        )
    else:
        print("Running normal incremental update...")
        updater.update_from_location(data_paths['s57_data_update_dir'])
    
    summary_df = updater.get_change_summary()
elif methods['S57_Updater']:
    print(f"S57Updater GeoPackage test skipped (backend = '{backend}', not 'gpkg')")
else:
    print("S57Updater test skipped (methods['S57_Updater'] = False)")

S57Updater test skipped (methods['S57_Updater'] = False)

## APPENDIX: Detailed Documentation

### A.1 S-57 Conversion Modes Explained

This notebook demonstrates comprehensive S-57 (Electronic Navigational Chart) conversion workflows
using the `nautical_graph_toolkit` library. Learn how to convert raw S-57 files to multiple backend formats
and verify data integrity across the conversion pipeline.

#### Conversion Modes

##### 1. **by_enc Mode** (S57Base)
- Each S-57 file becomes a separate output database/schema
- Useful for: Managing individual chart versions, isolated testing, source tracking
- Output structure: One schema per ENC (e.g., `US1EEZ1M`, `US1GC09M`)

##### 2. **by_layer Mode** (S57Advanced) - RECOMMENDED
- All S-57 files merged into a single database organized by object class (layer)
- Useful for: Unified analysis, spatial queries, performance optimization
- Features are stamped with `dsid_*` columns tracking source ENC, edition, and update
- Better for: Routing, maritime analysis, data fusion

#### Backend Targets
- **PostGIS**: Multi-user, server-based, enterprise-ready
- **GeoPackage**: Portable single file, works offline
- **SpatiaLite**: Self-contained SQLite, no external dependencies

#### Performance Considerations
- S57Advanced with `auto_tune_batch_size=True`: Automatically optimizes memory and I/O
- Parallel processing: Available for read-only file discovery (not database writes)
- Large datasets (10000+ ENCs): May take 2-4 hours depending on hardware

### A.2 Notebook Structure and Workflow

#### Notebook Organization

This notebook is organized into the following steps:

| Step | Name | Purpose | Duration |
|------|------|---------|----------|
| 1 | **Configuration** | Set backend, methods, and user parameters | 2 minutes |
| 2 | **Imports** | Load all dependencies and set environment | < 1 minute |
| 3 | **PostGIS Connection Test** | Verify database connectivity (if using PostGIS) | 1-2 seconds |
| 4 | **S57Base Conversions** | Quick one-to-one conversion (5-30 minutes) | 5-30 minutes |
| 5 | **S57Advanced Conversions** | Production layer-centric conversion (2-8 hours) | 2-8 hours |
| 6 | **S57Updater** | Incremental updates to maintain databases | 10-30 minutes |

### A.3 Simplified Configuration System

Instead of managing 14 individual workflow flags, the new system uses:

**Backend Selection:**
```python
backend = 'postgis'  # Options: 'postgis', 'spatialite', 'gpkg'
```

**Conversion Methods:**
```python
methods = {
    'S57_Base': True,          # Run S57Base conversions
    'S57_Advanced': True,      # Run S57Advanced conversions (RECOMMENDED)
    'S57_Updater': False       # Run S57Updater incremental updates
}
```

**Workflow Options:**
```python
workflow_options = {
    'run_parallel_processing': False,  # PostGIS only
}
```

### A.4 How to Use This Notebook

**For Quick Testing:**
```
backend = 'postgis'
methods = {'S57_Base': True, 'S57_Advanced': False, 'S57_Updater': False}
```
Run cells 1-4 (~5-30 minutes)

**For Production Setup:**
```
backend = 'postgis'
methods = {'S57_Base': True, 'S57_Advanced': True, 'S57_Updater': False}
```
Run cells 1-5 (~2-8 hours first time, includes validation)

**For Updates:**
```
backend = 'postgis'
methods = {'S57_Base': False, 'S57_Advanced': False, 'S57_Updater': True}
```
Run cells 1-3, then 6 (~10-30 minutes)

### A.5 Backend Notes

- **PostGIS**: All features supported (conversions, updates, parallel processing)
- **GeoPackage**: Conversions supported; updates may be constrained by concurrent access issues.
- **SpatiaLite**: Conversions supported; updates may be constrained by concurrent access issues.

### A.6 Important Pre-requisites

**For PostGIS Backend:**
- `.env` file must contain: `DB_NAME`, `DB_USER`, `DB_PASSWORD`, `DB_HOST`, `DB_PORT`
- Connection test (Step 3) will verify credentials

**Data Files:**
- S-57 ENC files in `data_paths['s57_data_dir']` (provided in test dataset)
- For S57Advanced, can optionally use larger dataset from `data_paths['active_enc']`

**Disk Space Requirements:**
- **S57Base conversions**: ~2-5x size of source .000 files
- **S57Advanced conversions**: ~3-8x size of source data (varies by backend and dataset size)
- **Recommended minimum**: 10GB free space for test datasets, 100GB+ for full NOAA ENC coverage
- **SpatiaLite**: Generally smaller than GeoPackage, fastest conversion time (~1 hour for NOAA data)
- **GeoPackage**: Moderate size, good for portable single-file deployments (~4 hours for NOAA data)
- **PostGIS**: No local file size limits, distributed storage across database